### ISSUE TITLE
Medical Segmentation Dechatlon

### ISSUE THREAD

**Issue by kurmukovai** [neuro-ml/amid#56]
Working on setting up interfaces for MSD, as seen at http://medicaldecathlon.com/, and we need to decide how to approach it. Do we go with separate interfaces for each subset, or one unified interface for all of them? I'm leaning towards the unified approach. For example, the brain subset is part of BraTS, which already has its own interface. The same is true for the Liver subset with LiTS, and possibly other sub-challenges.

**Comment by maxme1** [comment]
Do all the datasets from MSD have the same fields? Were they processed in any way? I guess we could start creating something like collections of datasets.

**Comment by kurmukovai** [comment]
Yeah, all subsets will end up with the same interface:
- all come as nifties, so `affine` and `spacing`,
- all contain a segmentation `mask`.
- every subset has built-in `train_test` splits. 

There are multiple image modalities including multi-sequence MRI, CT, and CE CT, so I am thinking to add `image_modality` and `task` for different subsets (01-Liver..10-Spleen). All in all having a unified interface seems reasonable.
